### ISSUE TITLE
Allow "always-on" remote forwarding

### ISSUE THREAD

**Issue by naftulikay** [topmedia/vagrant-remote-forward#1]
My organization requires users to tunnel a port over SSH to the shared database like so:

```
ssh -L 3306:localhost:3306 remotehost.mydomain.com
```

I then have to forward that port into my Vagrant box:

```
vagrant ssh -- -R 3306:localhost:3306
```

I then need to make sure that this SSH connection into the Vagrant box stays persistent. If it gets terminated, no database access.

I noticed that in your plugin, the port is only forwarded for the duration of the provisioner run, which seems to fit your use case of having it forward to a Chef server. Is there a way that we can make the SSH port forward a permanent one for the lifecycle of the machine? ie: whenever the VM is running, make sure that the remote forward is connected.

**Comment by scoop** [comment]
Vagrant doesn't keep running after a machine has been cloned/provisioned, so using this plugin won't help.

But what's keeping you from using regular, provider-based forwarded ports?
See: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

**Comment by naftulikay** [comment]
Vagrant's built-in functionality does local port forwarding so that `host:port` forwards to `guest:port`. I need the _opposite_ of that: `guest:port` forwards to `host:port`. That's what your plugin does, but only for the duration of the provisioning phase.

**Comment by scoop** [comment]
You're right of course.

Again, though, I don't see a way to do this with any kind of hook in vagrant because vagrant would have to stay running in the foreground for the port forward to be active since as soon as the process exits, so will any ssh processes it spawned.

Maybe you could try implementing your ssh command (potentially with the `-N` flag) with plugins like [vagrant-host-shell](https://github.com/phinze/vagrant-host-shell) or [vagrant-triggers](https://github.com/emyl/vagrant-triggers)? I'm not sure how they react if the command never really finishes.

**Comment by naftulikay** [comment]
Yeah, I've reported it as an issue with Vagrant proper. I might just have to commit upstream for this. Though I wish we could change our workflow, as is often the case in large companies, things take time. Thanks for considering this!
